management:
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    servlet:
      context-path: /actuator
server:
  port: 10000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          password: xxxx
          search-paths: dev
          skipSslValidation: true
          uri: https://github.com/SANDUO421/springcloud-config-repo.git
          username: sanduo421
    consul:
      discovery:
        health-check-interval: 10s
        health-check-path: ${management.server.servlet.context-path}/health
        instance-id: ${spring.application.name}
        prefer-ip-address: true
        register: true
      enabled: true
      host: ${consul-host:localhost}
      port: ${consul-port:8500}
  rabbitmq:
    host: 192.168.1.166
    password: tourism@permit
    port: 5672
    username: tourism-permit
