management:
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    servlet:
      context-path: /actuator
server:
  port: 9001
spring:
  application:
    name: monitor-test
  cloud:
    consul:
      discovery:
        health-check-interval: 10s
        health-check-path: ${management.server.servlet.context-path}/health
        instance-id: ${spring.application.name}
        prefer-ip-address: true
        register: true
      enabled: true
      host: ${consul-host:192.168.10.6}
      port: ${consul-port:8500}