management:
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: refresh,health,info
  server:
    servlet:
      context-path: /actuator
server:
  port: 9003
spring:
  application:
    name: springboot-mq
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      label: master
      name: ${spring.application.name}
      profile: dev
      uri: localhost:10000/
    consul:
      discovery:
        health-check-interval: 10s
        health-check-path: ${management.server.servlet.context-path}/health
        instance-id: ${spring.application.name}
        prefer-ip-address: true
        register: true
      enabled: true
      host: ${consul-host:localhost}
      port: ${consul-port:8500}
  rabbitmq:
    host: 192.168.10.9
    port: 5672
    username: tourism-permit
    password: tourism@permit
    connection-timeout: 6000
    publisher-confirms: true #消息发送到交换机确认机制，是否确认回调
    publisher-returns: true # 消息发送到交换机确认机制，是否返回回调
    listener:
      simple:
        acknowledge-mode: manual #手动应答
        concurrency: 1 #最小消费
        max-concurrency: 10 #最大消费
        retry:
          enabled: true #支持重试机制
